services:
  portfolio:
    build: .
    container_name: portfolio
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - web

networks:
  web:
    external: true
