name: Deploy to Private Server

on:
  push:
    tags:
      - 'v*'

env:
  DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.3.x'
    
    - name: Create .env.local file
      run: |
        echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env.local
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env.local
        echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env.local
        echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env.local
        echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env.local
        echo "EMAIL_TO=${{ secrets.EMAIL_TO }}" >> .env.local
        echo "NEXT_PUBLIC_RECAPTCHA_WEBSITE_KEY=${{ secrets.RECAPTCHA_WEBSITE_KEY }}" >> .env.local
        echo "RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}" >> .env.local
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
      run: |
        rsync -avz --delete -e "ssh -p $SERVER_PORT" \
          --exclude='.git' \
          --exclude='node_modules' \
          ./ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
    
    - name: Restart Application
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
      run: |
        ssh -p $SERVER_PORT $SERVER_USER@$SERVER_IP << EOF
          cd $DEPLOY_PATH
          docker-compose down
          docker-compose up -d --build
        EOF