# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t portfolio .

    - name: Run tests in Docker
      run: |
        docker run --rm portfolio npm ci
        docker run --rm portfolio npm run lint
        docker run --rm portfolio npm run build --if-present

    - name: Run container
      run: docker run -d -p 3000:3000 --name portfolio_container portfolio

    - name: Check if container is running
      run: docker ps | grep portfolio_container

    - name: Stop container
      run: docker stop portfolio_container
    